# This is a config for E2B sandbox template.
# You can use template ID (mmuei6qlpswcmdxh6cwm) or template name (spider-test-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("spider-test-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("spider-test-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('spider-test-2')

team_id = "4c5bafa7-cb8a-4688-affe-796f2760c36f"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "spider-test-2"
template_id = "mmuei6qlpswcmdxh6cwm"
